MedaProbe/Models/ErrorViewModel.cs
using System;

namespace CoreProbe1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MedaProbe/Controllers/EffectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CoreProbe1.Controllers
{
    public class EffectController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult VideoCube()
        {
            return View();
        }

        public IActionResult VideoClipped()
        {
            return View();
        }

        public IActionResult VideoZenit()
        {
            return View();
        }

        public IActionResult GoldStar()
        {
            return View();
        }
    }
}

MedaProbe/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CoreProbe1.Models;

namespace CoreProbe1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Start()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MedaProbe/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CoreProbe1.Controllers
{
    public class MediaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CameraRecognition()
        {
            return View();
        }

        public IActionResult CameraBackground()
        {
            return View();
        }

    }
}

MedaProbe/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CoreProbe1.Controllers
{
    public class SliderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ContentSlider()
        {
            return View();
        }

        public IActionResult LiquidSlider()
        {
            return View();
        }
    }
}

MedaProbe/Controllers/ThreeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MediaProbe.Controllers
{
    public class ThreeController : Controller
    {
        public IActionResult MusicProbe()
        {
            return View();
        }
      

    }
}

MedaProbe/Views/Effect/Forms/_NotSupported.cshtml
    <div class="not-supported">

        <p>Your browser doen't support <b>'mix-blend-mode'</b> CSS property!</p>
        <p>Use the latest <a class="browser logo-chrome" target="_blank" href="https://www.google.com/chrome/">Google Chrome</a> or <a class="browser logo-brave" target="_blank" href="https://brave.com/">Brave</a>.</p>
        <p>You can also check compatibility of the feature <a target="_blank" href="https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode#Browser_compatibility">here</a>.</p>

    </div>

MedaProbe/Views/Effect/Forms/_VideoEffectMenu.cshtml
<ul class="view-menu">
    <li><a href="@Url.Action("VideoCube", "Effect", new { id="" })">Video cube</a></li>
    <li><a href="@Url.Action("VideoClipped", "Effect", new { id="" })">Video clipped</a></li>
    <li><a href="@Url.Action("VideoZenit", "Effect", new { id="" })" title="Зенит-чемпион 2020!">Zenit 2020</a></li>
</ul>

MedaProbe/Views/Effect/GoldStar.cshtml
@{
    Layout = "_ViewLayout";

    ViewData["Title"] = "Gold Star";
}

@section head {
    <link rel="stylesheet" href="~/css/common/general.css" />
    <link rel="stylesheet" href="~/css/effect/goldstar.css" />
}

@section scripts {
    <script src="~/js/utils/util-dom.js"></script>
    <script src="~/js/utils/util-checker.js"></script>

    <script src="~/js/utils/util-test.js"></script>
}

<div class="shape">
    <div class="five-point-star"></div>
</div>
<div class="shape">
    <div class="five-point-star"></div>
</div>

<svg>
    <filter id="wavy">
        <feTurbulence x="0" y="0" baseFrequency="0.009" numOctaves="5" seed="2"></feTurbulence>
        <feDisplacementMap in2="SourceMap" scale="30"></feDisplacementMap>
    </filter>
</svg>

<script>

    document.addEventListener("DOMContentLoaded", () => {

        app.util.test.testFuncMethod();

    });

</script>

MedaProbe/Views/Effect/Index.cshtml
@{
    Layout = "_ViewLayout";

    ViewData["Title"] = "Index";
}

MedaProbe/Views/Effect/VideoClipped.cshtml
@{
    Layout = "_ViewLayout";

    ViewData["Title"] = "Video Clipping";
}

@section head {
    <link rel="stylesheet" href="~/css/common/general.css" />
    <link rel="stylesheet" href="~/css/effect/video-clipped.css" />
}

@section scripts {
    <script src="~/js/utils/util-dom.js"></script>
    <script src="~/js/utils/util-checker.js"></script>
}

@section viewmenu {
    <partial name="Forms/_VideoEffectMenu">
}

<div class="effect">

    <video autoplay muted loop crossorigin="anonymous"
           src="~/img/pictures/y2mate.com - ФК Зенит _ FC Zenit_Z95FaXRhKik_1080p.mp4">
    </video>

    <div class="text-box">
        <img class="logo" src="~/img/FC_Zenit_1_star_2015_logo.svg" />
        <span class="name">FC Zenit</span>
        <span class="city">Saint Petersburg</span>
    </div>

    <div class="audio-box">
        <div>
            <button id="play" class="off"></button>
            <audio id="player" loop src="~/media/y2mate.com - Ленинград - В Зените_fCPNqZu16uY.mp3"></audio>
        </div>
    </div>

</div>

<section id="templates">

    <template id="not-supported">
        <partial name="forms/_NotSupported" />
    </template>

</section>

<script type="text/javascript">

    function onReady() {

        const checker = new app.util.check.Checker();
        if (!checker.showNotSupportedProperties(["mixBlendMode"], "#templates #not-supported", "section.main")) return;

        var btn = document.getElementById("play");
        var player = document.getElementById("player");

        var togglePlay = function (e) {
            player.paused ? player.play() : player.pause();

            btn.classList.remove("off");
            btn.classList.remove("on");

            player.paused ? btn.classList.add("off") : btn.classList.add("on");

            document.activeElement.blur();
        }

        btn.addEventListener("click", togglePlay)

        document.addEventListener("keyup", togglePlay)

    }

    document.addEventListener("DOMContentLoaded", onReady);


</script>

MedaProbe/Views/Effect/VideoCube.cshtml
@{
    ViewData["Title"] = "Video Cube";

    Layout = "_ViewLayout";
}

@section head {
    <link rel="stylesheet" href="~/css/common/general.css" />
    <link rel="stylesheet" href="~/css/effect/video-cube.css" />
}

@section scripts {
    <script src="~/js/utils/util-dom.js"></script>
    <script src="~/js/utils/util-checker.js"></script>
}

@section viewmenu {
    <partial name="Forms/_VideoEffectMenu">
}

<div class="effect">

    <video autoplay muted loop src="~/media/y2mate.com - Transient - 4K, UHD, 1000FPS_nBYZpsbu9ds_1080p.mp4">
    </video>

    <div class="box">
        <div>
            <span>
                <video autoplay muted loop src="~/media/y2mate.com - Transient 2 - 4K, UHD, 1000FPS_tq1mxZZIuIY_1080p.mp4"></video>
            </span>
            <span>
                <video autoplay muted loop src="~/media/y2mate.com - Transient 2 - 4K, UHD, 1000FPS_tq1mxZZIuIY_1080p.mp4"></video>
            </span>
            <span>
                <video autoplay muted loop src="~/media/y2mate.com - Transient 2 - 4K, UHD, 1000FPS_tq1mxZZIuIY_1080p.mp4"></video>
            </span>
        </div>
    </div>

</div>

<section id="templates">

    <template id="not-supported">
        <partial name="forms/_NotSupported" />
    </template>

</section>

<script type="text/javascript">

    function onReady() {
        const checker = new app.util.check.Checker();
        if (!checker.showNotSupportedProperties(["mixBlendMode"], "#templates #not-supported", "div.effect")) return;
    }

    document.addEventListener("DOMContentLoaded", onReady);


</script>

MedaProbe/Views/Effect/VideoZenit.cshtml
@{
    Layout = "_ViewLayout";

    ViewData["Title"] = "Video Zenit";
}

@section head {
    <link rel="stylesheet" href="~/css/common/general.css" />
    <link rel="stylesheet" href="~/css/effect/video-zenit.css" />
}

@section scripts {
    <script src="~/js/utils/util-dom.js"></script>
    <script src="~/js/utils/util-checker.js"></script>
}

@section viewmenu {
    <partial name="Forms/_VideoEffectMenu">
}


<div class="effect">

    <video autoplay muted loop crossorigin="anonymous"
           src="~/media/y2mate.com - «Мы Чемпионы!», «Зенит» – чемпион России по футболу в сезоне 20192020._1080pFHR.mp4">
    </video>

    <div class="shade"></div>

    <svg class="banner banner-view-animation" viewBox="0 0 300 100">
        <text x="50%" y="50%" text-anchor="middle">Зенит - чемпион!</text>
        <text x="50%" y="70%" text-anchor="middle">2020</text>
    </svg>

    <div class="audio-box">
        <div>
            <button id="play" class="off"></button>
            <audio id="player" loop src="~/media/y2mate.com - Ленинград - В Зените_fCPNqZu16uY.mp3"></audio>
        </div>
    </div>

</div>


<script type="text/javascript">

    function onReady() {

        const checker = new app.util.check.Checker();
        if (!checker.showNotSupportedProperties(["mixBlendMode"], "#templates #not-supported", "section.main")) return;

        const bannerAnimClass = "banner-view-animation";
        const bannerEndAnim = "anim-banner-hide";

        var effect = document.querySelector(".effect");
        var banner = document.querySelector(".banner");

        var btn = document.getElementById("play");
        var player = document.getElementById("player");

        var togglePlay = function (e) {
            player.paused ? player.play() : player.pause();

            btn.classList.remove("off");
            btn.classList.remove("on");

            player.paused ? btn.classList.add("off") : btn.classList.add("on");

            document.activeElement.blur();
        }

        btn.addEventListener("click", togglePlay)

        document.addEventListener("keyup", togglePlay)

        effect.addEventListener("mousemove", ev => {
            if (!banner.classList.contains(bannerAnimClass)) {
                banner.classList.add(bannerAnimClass);
            }
        });

        banner.addEventListener("animationend", ev => {
            if (ev.animationName != bannerEndAnim) return;
            banner.classList.remove(bannerAnimClass);
        });

    }

    document.addEventListener("DOMContentLoaded", onReady);


</script>

MedaProbe/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MedaProbe/Views/Home/Start.cshtml
@{
    ViewData["Title"] = "Start";
    Layout = "_MasterLayout";
}

@section head {
    <link rel="stylesheet" href="~/css/menu/start-menu.css" />
}

<nav class="navigation">
    <ul>
        @*<li><a href="#" data-text="Home" style="--bkc:#81ecec">Home</a></li>*@
        <li><a href="@Url.Action("CameraRecognition", "Media", new { id="" })" data-text="Camera Features" style="--bkc:#55efc4">Camera Features</a></li>
        <li><a href="@Url.Action("VideoCube", "Effect", new { id="" })" data-text="Video Effects" style="--bkc:#a29bfe">Video Effects</a></li>
        <li><a href="@Url.Action("ContentSlider", "Slider", new { id="" })" data-text="Sliders" style="--bkc:#ff7675">Sliders</a></li>
        @*<li><a href="#" data-text="About"style="--bkc:#fd79a8">About</a></li>*@
    </ul>
</nav>

@*embed a credit badge.*@
@*Photo by Gem Lyn on Unsplash*@

MedaProbe/Views/Media/CameraBackground.cshtml
@{
    Layout = "_ViewLayout";

    ViewData["Title"] = "Camera Recognition";
}

@section head {
    <link rel="stylesheet" href="~/css/common/general.css" />
    <link rel="stylesheet" href="~/css/common/loading.css" />
    <link rel="stylesheet" href="~/css/media/media.css" />
    <link rel="stylesheet" href="~/css/media/presets.css" />

    <!-- Load TensorFlow.js -->
    <!--<script src="https://cdn.jsdelivr.net/npm/@@tensorflow/tfjs@1.2"></script>-->
    <!-- Load BodyPix -->
    <!--<script src="https://cdn.jsdelivr.net/npm/@@tensorflow-models/body-pix@2.0"></script>-->

}

@section scripts {
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.2.4/pixi.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/TweenMax.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/pixi-filters@latest/dist/pixi-filters.js"></script>

    <script src="~/js/utils/util-dom.js"></script>
    <script src="~/js/utils/util-image.js"></script>
    <script src="~/js/utils/util-checker.js"></script>

    <script src="~/js/pixi/filters.js"></script>

    <script src="~/js/media/camcorder.js"></script>
    <script src="~/js/media/camera-background.js"></script>

}

@section viewmenu {
    <partial name="Forms/_CamcoderMenu">
}

<div class="container">

    <section id="camera-party">

        <div id="player" class="video-player">

            <div class="startup-text">&#9733; it shows camera here &#9733;</div>

            <canvas id="cadre" class="d-none"></canvas>
            <canvas id="capture"></canvas>
            <video id="video" autoplay class="d-none"></video>
            <canvas id="overlay"></canvas>

            <div class="controls">
                <div class="options">
                    <div class="video-options">
                        <select name="" id="" class="custom-select" title="Select camera">
                            <option value="">Select camera</option>
                        </select>
                    </div>
                    <div class="video-ratio">
                        <select name="" id="" class="custom-select" title="Select screen ratio">
                            <option value="">Select ratio</option>
                        </select>
                    </div>
                    <div class="detect-quality">
                        <select name="" id="" class="custom-select" title="Select detection quality">
                            <option value="">Select detect resolution</option>
                        </select>
                    </div>
                </div>
                <div class="buttons">
                    <button class="btn btn-danger play" title="Play"><i data-feather="play-circle"></i></button>
                    <button class="btn btn-info pause d-none" title="Pause"><i data-feather="pause"></i></button>
                    <button class="btn btn-outline-success d-none" title="Screenshot"><i data-feather="image"></i></button>
                    <button class="btn btn-outline-warning d-none" title="Recognize"><i data-feather="activity"></i></button>
                </div>
            </div>

        </div>

        <div class="video-preset">
            <h3>Backgrounds</h3>
            <partial name="Forms/_BackgroundList" />
        </div>

        <div class="video-preset">
            <h3>Effects</h3>
            <partial name="Forms/_FilterList" />
        </div>

        <div class="video-preset">
            <h3>Snapshots</h3>
            <partial name="Forms/_ScreenshotList" />
        </div>

    </section>

    <section id="templates">

        <template id="loading-indicator">
            <partial name="common/_loading" />
        </template>

        <template id="background-item">
            <partial name="forms/_BackgroundItem" />
        </template>

        <template id="screenshot-item">
            <partial name="forms/_ScreenshotItem" />
        </template>

        <template id="not-supported">
            <partial name="forms/_NotSupported" />
        </template>

    </section>

</div>


<script type="text/javascript">

    document.addEventListener("DOMContentLoaded", async () => {

        feather.replace();

        const checker = new app.util.check.Checker();
        if (!checker.showNotSupportedObjects(["ImageCapture"], "#templates #not-supported", "section.main")) return;

        var camera = new app.media.CameraBackground(document.getElementById("camera-party"),
            {
                debugLog: true,
                detectorWorkerScriptUrl: "@(Url.Content("~/js/media/detector-bodypix.js") + "?_=" + DateTime.Now.Millisecond))",
                displacementImage: "@Url.Content("~/img/liquids/dmaps/512x512/clouds.jpg")",
            });

    });

</script>

MedaProbe/Views/Media/CameraRecognition.cshtml
@{
    Layout = "_ViewLayout";

    ViewData["Title"] = "Camera Recognition";
}

@section head {
    <link rel="stylesheet" href="~/css/common/general.css" />
    <link rel="stylesheet" href="~/css/common/loading.css" />
    <link rel="stylesheet" href="~/css/media/media.css" />
}

@section scripts {
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="~/js/utils/util-dom.js"></script>
    <script src="~/js/utils/util-image.js"></script>
    <script src="~/js/utils/util-checker.js"></script>
    <script src="~/js/media/camera.js"></script>
}

@section viewmenu {
    <partial name="Forms/_CamcoderMenu">
}

<div class="container">

    <section id="camera-party">

        <div id="player" class="video-player">

            <div class="startup-text">&#9733; it shows camera here &#9733;</div>

            <canvas id="capture"></canvas>
            <video id="video" autoplay></video>
            <canvas id="overlay"></canvas>

            <div class="controls">
                <div class="options">
                    <div class="video-options">
                        <select name="" id="" class="custom-select">
                            <option value="">Select camera</option>
                        </select>
                    </div>
                    <div class="video-ratio">
                        <select name="" id="" class="custom-select">
                            <option value="">Select ratio</option>
                        </select>
                    </div>
                </div>
                <div class="buttons">
                    <button class="btn btn-danger play" title="Play"><i data-feather="play-circle"></i></button>
                    <button class="btn btn-info pause d-none" title="Pause"><i data-feather="pause"></i></button>
                    <button class="btn btn-outline-success d-none" title="Screenshot"><i data-feather="image"></i></button>
                    <button class="btn btn-outline-warning d-none" title="Recognize"><i data-feather="activity"></i></button>
                </div>
            </div>

        </div>

        <div class="video-detect d-none">
            <canvas id="source-canvas"></canvas>
        </div>

        <div class="video-screenshot">
            <ul class="screenshot-list"></ul>
        </div>

    </section>

    <section id="templates">

        <template id="screenshot-item">
            <img id="screenshot" />
            <div class="screenshot-ctrl">
                <button class="screenshot-download" title="Download"></button>
                <button class="screenshot-remove" title="Remove"></button>
            </div>
            <div class="screenshot-info">
            </div>
        </template>

        <template id="loading-indicator">
            <partial name="common/_loading" />
        </template>

        <template id="not-supported">
            <partial name="forms/_NotSupported" />
        </template>

    </section>

</div>

<script type="text/javascript">

    document.addEventListener("DOMContentLoaded", async () => {

        feather.replace();

        const checker = new app.util.check.Checker();
        if (!checker.showNotSupportedObjects(["ImageCapture"], "#templates #not-supported", "section.main")) return;

        var cameraParty = new app.media.CameraParty(document.getElementById("camera-party"),
            {
                detectorWorkerScriptUrl: "@Url.Content("~/js/media/detector.js")",
                debugLog : false
            });

});

</script>

MedaProbe/Views/Media/Forms/_BackgroundItem.cshtml
<li class="preset-item">
    <label>
        <input type="radio" name="background-option" value="image" />
        <img class="content" />
        <span class="tick-frame"></span>
        <span class="ctrl-frame">
            <button class="item-remove" title="Remove"></button>
        </span>
    </label>
</li>

MedaProbe/Views/Media/Forms/_BackgroundList.cshtml
<ul class="preset-list background-list">
    <li class="preset-item">
        <label>
            <input type="radio" name="background-option" value="video" checked="checked" />
            <span class="content" data-name="No background"></span>
            <span class="tick-frame"></span>
        </label>
    </li>
    <li class="preset-item">
        <label>
            <input type="radio" name="background-option" value="image" />
            <img class="content" src="~/img/camera/bk-pic01.jpg" />
            <span class="tick-frame"></span>
        </label>
    </li>
    <li class="preset-item">
        <label>
            <input type="radio" name="background-option" value="image" />
            <img class="content" src="~/img/camera/bk-pic02.jpg" />
            <span class="tick-frame"></span>
        </label>
    </li>
    <li class="preset-item">
        <label>
            <input type="radio" name="background-option" value="image" />
            <img class="content" src="~/img/camera/bk-pic03.jpg" />
            <span class="tick-frame"></span>
        </label>
    </li>
    <li class="preset-item">
        <label>
            <input type="radio" name="background-option" value="image" />
            <img class="content" src="~/img/camera/bk-pic04.jpg" />
            <span class="tick-frame"></span>
        </label>
    </li>
    <li class="preset-item">
        <label>
            <input type="radio" name="background-option" value="image" />
            <img class="content" src="~/img/camera/bk-pic05.jpg" />
            <span class="tick-frame"></span>
        </label>
    </li>
    <li class="preset-item">
        <label>
            <input type="radio" name="background-option" value="image" />
            <img class="content" src="~/img/camera/bk-pic06.jpg" />
            <span class="tick-frame"></span>
        </label>
    </li>
    <li class="preset-item">
        <div class="content">
            <div class="upload">
                <button class="btn btn-light" title="Upload image" 
                        onclick="javascript: this.parentNode.querySelector('input[type=file]').click()">
                    Upload
                </button>
                <input type="file" accept="image/*" />
            </div>
        </div>
    </li>
</ul>

MedaProbe/Views/Media/Forms/_CamcoderMenu.cshtml
<ul class="view-menu">
    <li><a href="@Url.Action("CameraRecognition", "Media", new { id="" })" title="Object Detection">Camera & Coco SSD</a></li>
    <li><a href="@Url.Action("CameraBackground", "Media", new { id="" })" title="Person Detection">Camera, Pixi & Body Pix</a></li>
</ul>

MedaProbe/Views/Media/Forms/_FilterList.cshtml
<ul class="preset-list filter-list">
    <li class="preset-item">
        <label>
            <input type="checkbox" name="filter-option" value="blur">
            <img class="content" src="~/img/camera/filter-blur.jpg" />
            <span class="preset-info">Blur</span>
            <span class="tick-frame"></span>
        </label>
    </li>
    <li class="preset-item">
        <label>
            <input type="checkbox" name="filter-option" value="kawaseblur">
            <img class="content" src="~/img/camera/filter-kawaseblur.jpeg" />
            <span class="preset-info">Kawase blur</span>
            <span class="tick-frame"></span>
        </label>
    </li>
    <li class="preset-item">
        <label>
            <input type="checkbox" name="filter-option" value="motionblur">
            <img class="content" src="~/img/camera/filter-motionblur.jpg" />
            <span class="preset-info">Motion blur</span>
            <span class="tick-frame"></span>
        </label>
    </li>
    <li class="preset-item">
        <label>
            <input type="checkbox" name="filter-option" value="liquid">
            <img class="content" src="~/img/camera/filter-displacement.jpg" />
            <span class="preset-info">Liquid</span>
            <span class="tick-frame"></span>
        </label>
    </li>
    <li class="preset-item">
        <label>
            <input type="checkbox" name="filter-option" value="shockwave">
            <img class="content" src="~/img/camera/filter-shockwave.jpeg" />
            <span class="preset-info">Shockwave</span>
            <span class="tick-frame"></span>
        </label>
    </li>
    <li class="preset-item">
        <label>
            <input type="checkbox" name="filter-option" value="fisheye">
            <img class="content" src="~/img/camera/filter-fisheye.jpeg" />
            <span class="preset-info">Fisheye</span>
            <span class="tick-frame"></span>
        </label>
    </li>
</ul>

MedaProbe/Views/Media/Forms/_ScreenshotItem.cshtml
<li class="preset-item">
    <img class="content" />
    <span class="ctrl-frame">
        <button class="item-download" title="Download"></button>
        <button class="item-remove" title="Remove"></button>
    </span>
    <span class="preset-info"></span>
</li>

MedaProbe/Views/Media/Index.cshtml
@{
    Layout = "_ViewLayout";

    ViewData["Title"] = "Index";
}

@section head {
    <link rel="stylesheet" href="~/css/common/loading.css" />
}


<partial name="common/_loading" />

MedaProbe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreProbe1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreProbe1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Media" asp-action="Index">Media</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Effect" asp-action="Index">Effect</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CoreProbe1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MedaProbe/Views/Slider/Forms/_SlidersMenu.cshtml
<ul class="view-menu">
    <li><a href="@Url.Action("ContentSlider", "Slider", new { id="" })">Content slider</a></li>
    <li><a href="@Url.Action("LiquidSlider", "Slider", new { id="" })">Liquid slider</a></li>
</ul>